### ISSUE TITLE
[BUG]: cannot mount local to /home/jovyan/work

### ISSUE THREAD

**Issue by asreimer** [EarthCubeInGeo/resen#12]
It is intended that users can add storage mounting locations to `/home/jovyan/work` and onto or into locations inside of `/home/jovyan/mount`. 

Currently, it is impossible to mount directly to `/home/jovyan/work`:

    (env3.7) [asreimer@thomson ~]$ resen
        ___ ___ ___ ___ _  _ 
       | _ \ __/ __| __| \| |
       |   / _|\__ \ _|| .` |
       |_|_\___|___/___|_|\_|
    
    Resen 19.1.0 -- Reproducible Software Environment
    
    [resen] >>> create_bucket test
    [resen] >>> add_image test 2019.1.0rc1
    [resen] >>> add_storage test /home/asreimer/temp/bucket /home/jovyan/work/ rw
    ERROR: Invalid mount location. Can only mount storage into: /home/jovyan/work, /home/jovyan/mount.

[This is the code that needs to be modified to enable this.](https://github.com/EarthCubeInGeo/resen/blob/develop/resen/Resen.py#L304-L313)

**Comment by pmreyes2** [comment]
PR #21 fixes this issue.
