### ISSUE TITLE
[ENH]: Dockerfile missing ipython 2 kernel

### ISSUE THREAD

**Issue by ljlamarche** [EarthCubeInGeo/resen#2]
When testing tutorials in the resen docker image, I cannot run python2 without installing additional conda packages. The python2 kernel is not registered with jupyter notebook.

Here's what I did:
1) start docker container and enter a bash shell in it
2) `source activate python2`
3) `jupyter notebook --port 8000`

and the notebook server only sees the default conda python3.6 environment.

Solutions: https://stackoverflow.com/questions/30492623/using-both-python-2-x-and-python-3-x-in-ipython-notebook

Also, what is all this "not trusted" stuff in the notebook server?

**Comment by asreimer** [comment]
Moved all docker stuff into resen-core. Will address it there.
