### ISSUE TITLE
Jupyter server crashes if attempting to view hdf5 file

### ISSUE THREAD

**Issue by ljlamarche** [EarthCubeInGeo/resen#37]
Currently, if you try to click on an hdf5 file in your jupyter work space, the jupyter server crashes, giving this pop up message.
![Screen Shot 2019-07-08 at 10 10 11 AM](https://user-images.githubusercontent.com/23563101/60837771-e36bfd80-a17d-11e9-9d83-bd9d5188379b.png)

Clicking "DISMISS" results in the following more informative pop up message.
![Screen Shot 2019-07-08 at 1 05 36 PM](https://user-images.githubusercontent.com/23563101/60839230-81ad9280-a181-11e9-8d6b-e5a3596e4133.png)

However, you can't do anything in jupyter lab anymore and just have to close the browser window.

The status of the bucket is still listed as `running`.
```
[resen] >>> status
Bucket Name         Docker Image             Status                   
satpy_test          2019.1.0rc2              exited                   
certo_sigma         2019.1.0rc2              running                  
```

If you close the jupyter window in the browser, then restart the jupyter notebook, the jupyter server seems to start again without issues.
```
[resen] >>> start_jupyter certo_sigma
```

I was definitely doing something I shouldn't have been doing here (viewing hdf5 files is not currently supported by jupyter lab, there are some discussions about adding it! https://github.com/jupyterlab/jupyterlab/issues/5323 https://github.com/jupyterlab/jupyterlab/issues/448), but the server crashing is not the best.  If I try to open an hdf5 file in a jupyter lab server running just on my computer (not in a bucket), I get a pop up with a File Load Error, but I don't have to restart the server.

Two things to consider:
1. Should jupyterlab that is shipped with resen-core include some kind of viewing capabilities for hdf5/cdf4 files?  This would probably be incredibly useful, but may be extremely difficult, although it looks like there are some existing projects that might be helpful starting points (i.e. https://github.com/HDFGroup/h5serv or https://github.com/m-rossi/hdf5widget).
2. If not, can we get the jupyter lab running in a bucket to just show the normal "File Load" error and not require the jupyter server to be restarted?

**Comment by pmreyes2** [comment]
I can not reproduce the error on a jupyterlab serving from the latest resen tool and resen-core rc2. I get the File Load Error pop up either in Firefox, Chrome or Safari. I test it by double clicking some AMISR *.h5 rawdata files mounted in /home/jovyan/mnt as read only. I'll keep testing to reproduce the error.
That said, it would be great if one can double click not only on HDF5 files and see the structure, but also numpy npz files or matlab data files, etc. Maybe it is not that difficult to include.

**Comment by ljlamarche** [comment]
Hmm, I'm still having this issue with Firefox.   It's happening with a 5.7G fitted AMISR file that's mounted to /home/jovyan/mount from my local machine (read-only).  I'm using version 2019.1.0rc2 of both resen and resen-core.

**Comment by pmreyes2** [comment]
Ok. I was able to reproduce the error on the resen tool on my mac trying to open a 3.7 GB h5 file.

**Comment by ljlamarche** [comment]
Ok, so it looks like the file size makes a big difference.  Attempting to open small files (a couple of MB) just give the standard "File Load Error".  Attempting to open large files gives a "Server Connection Error", but I'm not sure exactly where the cutoff between "small" and "large" is.  Also, we should investigate if this is a standard problem that happens any time you try to open a large file or if it's specific to hdf5 (I suspect it's not). @pmreyes2 noticed that the environment I was trying this in on my local machine had a more recent of jupyter and jupyterlab than what is in resen-core.  I haven't found any reference to that being a specific known issue with older versions of jupyter lab, but it's possible it's a factor.

**Comment by asreimer** [comment]
This seems like it's a problem specific to jupyter and it will also be dependent on system memory/resources. To answer point 2 in the original post, one would need to look at the jupyter source code and see what exactly it is doing to determine if one could prevent it from crashing/getting killed.

The two pop-ups you are seeing are not python, but javascript running in the browser client. The server has already crashed under the hood.

To answer point 1, h5serv won't help, but hdf5widget looks useful!

**Comment by ljlamarche** [comment]
Just to be complete, [jupyterlab-hdf](https://github.com/jupyterlab/jupyterlab-hdf5) is a jupyter lab extension that we may also want to consider for this purpose.  The project is fairly new, but it's vision seems to be exactly what we'd want to do.

**Comment by asreimer** [comment]
This issue was resolved with: https://github.com/EarthCubeInGeo/resen-core/pull/45/commits/37ed6bc5cbf6a9ede1ff35933dee8e25b6a582eb
