### ISSUE TITLE
%matplotlib notebook

### ISSUE THREAD

**Issue by bharding512** [EarthCubeInGeo/resen#57]
The Resen tutorials use "%matplotlib inline" which works great. I've found "%matplotlib notebook" to be useful, to be able to zoom and pan. I'm not sure if that's possible to support in the online interface, but it would be great to have.

**Comment by asreimer** [comment]
Hey @bharding512, are you using `%matplotlib notebook` with `jupyterlab`? What version of `python`, `jupyter`, and `matplotlib` are you using?

**Comment by pmreyes2** [comment]
@bharding512  interactive `matplotlib` plots would be a great addition. By default we are using `JupyterLab` which seems not to be supporting `%matplotlib notebook`. ( see [JupyterLab#2948](https://github.com/jupyterlab/jupyterlab/issues/2948) ). Apparently the alternative for `JupyterLab` is to use either `%matplotlib widget` or `%matplotlib ipympl`. We will look into it.
The `%matplotlib notebook` capability works in the `classical notebook` that you can access from `JupyterLab` by clicking on menu _Help_ -> _Launch Classic Notebook_
<img width="661" alt="Screen Shot 2020-04-02 at 1 22 38 PM" src="https://user-images.githubusercontent.com/3052100/78297775-24165e80-74e5-11ea-905d-47ad959766ad.png">

**Comment by bharding512** [comment]
Oh, didn't realize that was a Jupyterlab limitation. Thanks for the quick response.

**Comment by pmreyes2** [comment]
Well `Jupyterlab` has the nice equivalent enabled by `%matplotlib widget`
which can be installed following instructions here:
[https://github.com/matplotlib/ipympl](https://github.com/matplotlib/ipympl)

**Comment by pmreyes2** [comment]
This will be considered in the next version of resen-core. There is a list of suggestions/requests to consider for the next version here: [resen-core#42](https://github.com/EarthCubeInGeo/resen-core/issues/42)
