### ISSUE TITLE
[DOC] Improve documentation

### ISSUE THREAD

**Issue by asreimer** [EarthCubeInGeo/resen#58]
- [x] Make mounting more clear (differentiate between host and bucket)
- [x] Expand export documentation (e.g. what is default export location?)
- [x] Highlight linux postinstall gotchas (https://docs.docker.com/engine/install/linux-postinstall/)

**Comment by ljlamarche** [comment]
Additional information on mounting: ee2c62cbfbe2283c70fa2d62642d7e2c1fc7dc3d

**Comment by ljlamarche** [comment]
Export documentation expanded: 29247ce22fe08d86fc7a78fd69effc397619ddb2

**Comment by ljlamarche** [comment]
@asreimer, can you either add the linux post-installs link to the improve_docs branch or let me know where it should go?  I've completed the other additions, so feel free to look through the documentation on this branch and correct/clarify anything!

**Comment by ljlamarche** [comment]
Linux post-installation: 935dc5f1f47da42558cc3e8bff9aecdccea6cfaa

**Comment by ljlamarche** [comment]
These improvements have been merged into develop (#69).
