### ISSUE TITLE
[ENH]: Adding custom resen-cores

### ISSUE THREAD

**Issue by ljlamarche** [EarthCubeInGeo/resen#64]
The big goal for the next major release of resen is making the tool flexible enough so custom cores can be used with it.  Some things to consider:

- It's straightforward enough to read in the available cores from a json file instead of a hard-coded dictionary in the source code (see `core_list` branch).  Where should this file be kept on the users computer?  Should we instruct users to modify it manually or add an `add_core` command in resen that prompts users with a list of questions similar to how buckets are set up?
- Can we get the "standard" list of cores by querying docker hub? This might simplify letting users maintain their own library of custom cores but also updating the list of available cores every time a new resen-core is released.
- What characteristics does a core need to be compatible with resen?
- Should we have naming/metadata conventions?
- Are there any considerations needed for the server?

**Comment by ljlamarche** [comment]
This is potentially useful for determining the list of cores from docker hub (thanks @pmreyes2):
https://stackoverflow.com/questions/44834211/download-size-of-docker-images

**Comment by asreimer** [comment]
Summary of discussion today:
- main list of "official" resen-cores available by default
    - can be updated by a command (`update`? Would pull the [cores.json](https://github.com/EarthCubeInGeo/resen-core/blob/master/cores.json) in the resen-core repo)
- user can add cores by adding a json file per core into a `config.d` style directory
    - custom user cores will only work if built from an official resen-core image


No decision on a date to complete by.

**Comment by ljlamarche** [comment]
PR #67 adds some of the background functionality we'll need for this.  Cores are now read from JSON files located in the `cores` directory in the resen config directory.  If this directory is empty, resen downloads the default core list from the resen-core repo (https://github.com/EarthCubeInGeo/resen-core/blob/master/cores.json).  Resen will also download this file if you run the `update` command, allowing users to update the list of cores if there's a new release without updating resen.  In theory, users can now add their own cores by either adding additional entries to `cores.json`, or additional json files to this directory.  This is not user friendly and will likely not be the recommended way to add cores, so this not currently documented.
