### ISSUE TITLE
program breaks when creating bucket with no name

### ISSUE THREAD

**Issue by pmreyes2** [EarthCubeInGeo/resen#66]
The program breaks when creating a bucket with no name. Instead of breaking it should warn the user that no name is given, similar as it warns the user when the name does not start with an alphabetic character. The following GIF illustrates the issue: Attempt to create a bucket with a name that starts with a number, so a warning is given. Then, in a second attempt, no name is given and the program crashes.

![create_no_name](https://user-images.githubusercontent.com/3052100/86944956-4aa7ef00-c0fd-11ea-8945-a9318b5dc5e6.gif)

**Comment by ljlamarche** [comment]
Solved by d6b2292c740e4fea2c1b602705434f3e61f2d2e8.  An additional check was added to get_valid_name() function to make sure the name is not an empty string.
